ReversiApp/Models/Spel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;

namespace ReversiApp.Models
{
    public class Spel : ISpel
    {
        public int ID { get; set; }
        public string Omschrijving { get; set; }
        public string Token { get; set; }
        public string SerializeBord
        {
            get => JsonConvert.SerializeObject(Bord);
            set => Bord = JsonConvert.DeserializeObject<Kleur[,]>(value);
        }
        [NotMapped]
        public Kleur[,] Bord { get; set; } = new Kleur[8, 8];
        public Kleur AandeBeurt { get; set; } = Kleur.Zwart;
        private List<(int, int)> PossibleDirection { get; set; } = new List<(int, int)>();
        public List<Speler> Spelers { get; set; }

        public Spel()
        {
            // generate new unique token
            var g = Guid.NewGuid();
            var GuidString = g.ToString().Replace("&", "");
            

            Token = GuidString;

            // initialize middle of bord
            Bord[3, 3] = Kleur.Wit;
            Bord[4, 3] = Kleur.Zwart;
            Bord[3, 4] = Kleur.Zwart;
            Bord[4, 4] = Kleur.Wit;

            SerializeBord = JsonConvert.SerializeObject(Bord);
        }
        public bool Pas()
        {
            // check if there is a play possible
            for (var row = 0; row < Bord.GetLength(0); row++)
            {
                for (var col = 0; col < Bord.GetLength(1); col++)
                {
                    // if there is a play possible, then you may not pass the turn
                    var canPlay = CheckPlay(row, col, AandeBeurt);
                    if (canPlay) return false;
                }
            }

            // switch color
            AandeBeurt = OppositeColor(AandeBeurt);
            return true;
        }

        public bool Afgelopen()
        {
            // for each field, check if a move is possible
            for (var row = 0; row < Bord.GetLength(0); row++)
            {
                for (var col = 0; col < Bord.GetLength(1); col++)
                {
                    // check if white can play
                    var whiteCanPlay = CheckPlay(row, col, Kleur.Zwart);
                    // check if black can play
                    var blackCanPlay = CheckPlay(row, col, Kleur.Wit);
                    // if white or black can still play, return false
                    if (whiteCanPlay || blackCanPlay) return false;
                }
            }

            // if there is no move found, the game is over
            return true;
        }

        public Kleur OverwegendeKleur()
        {
            // initialize variables
            var white = 0;
            var black = 0;

            // check colors on the board
            foreach (var color in Bord)
            {
                switch (color)
                {
                    case Kleur.Wit:
                        white++;
                        break;
                    case Kleur.Zwart:
                        black++;
                        break;
                    case Kleur.Geen:
                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }

            // return color
            return white == black ? Kleur.Geen : white < black ? Kleur.Zwart : Kleur.Wit;
        }

        public bool ZetMogelijk(int rijZet, int kolomZet)
        {
            return CheckPlay(rijZet, kolomZet, AandeBeurt);
        }

        public bool DoeZet(int rowSet, int colSet)
        {
            if (!ZetMogelijk(rowSet, colSet)) return false;

            // place set
            Bord[rowSet, colSet] = AandeBeurt;

            // turn tiles
            foreach (var (r, c) in PossibleDirection)
            {
                Bord[r, c] = AandeBeurt;
            }

            // switch turn
            AandeBeurt = OppositeColor(AandeBeurt);

            return true;
        }

        public static Kleur OppositeColor(Kleur color)
        {
            // return opposite color
            return color switch
            {
                Kleur.Geen => Kleur.Geen,
                Kleur.Wit => Kleur.Zwart,
                Kleur.Zwart => Kleur.Wit,
                _ => Kleur.Geen
            };
        }

        private bool CheckPlay(int row, int col, Kleur color)
        {
            // initialize variables
            var turnLocations = new List<(int, int)>();

            // check possible directions to go
            var possibleDirections = GetPossibleDirections(row, col, color);

            // when no directions are possible return false
            if (possibleDirections.Count == 0) return false;

            // loop through all possibilities
            foreach (var direction in possibleDirections)
            {
                var options = CheckDirectionForPlays(direction, (row, col));
                foreach (var (item1, item2) in options)
                {
                    turnLocations.Add((item1, item2));
                }
            }

            PossibleDirection = turnLocations;

            return PossibleDirection.Count > 0;
        }

        private List<(int, int)> CheckDirectionForPlays(Direction direction, (int, int) place)
        {
            var (row, col) = place;
            var temp = new List<(int, int)>();
            var foundSelf = false;
            var rowCounter = row;
            var colCounter = col;

            switch (direction)
            {
                case Direction.North:
                    rowCounter--;
                    while (rowCounter > 0)
                    {
                        if (Bord[rowCounter, colCounter] == OppositeColor(AandeBeurt))
                        {
                            temp.Add((rowCounter, colCounter));
                        }
                        else if (Bord[rowCounter, colCounter] == AandeBeurt)
                        {
                            foundSelf = true;
                            break;
                        }
                        else
                            break;
                        rowCounter--;
                    }
                    break;
                case Direction.NorthEast:
                    rowCounter--;
                    colCounter++;
                    while (rowCounter >= 0 && colCounter < 8)
                    {
                        if (Bord[rowCounter, colCounter] == OppositeColor(AandeBeurt))
                        {
                            temp.Add((rowCounter, colCounter));
                        }
                        else if (Bord[rowCounter, colCounter] == AandeBeurt)
                        {
                            foundSelf = true;
                            break;
                        }
                        else
                            break;
                        rowCounter--;
                        colCounter++;
                    }
                    break;
                case Direction.East:
                    colCounter++;
                    while (colCounter < 8)
                    {
                        if (Bord[rowCounter, colCounter] == OppositeColor(AandeBeurt))
                        {
                            temp.Add((rowCounter, colCounter));
                        }
                        else if (Bord[rowCounter, colCounter] == AandeBeurt)
                        {
                            foundSelf = true;
                            break;
                        }
                        else
                            break;
                        colCounter++;
                    }
                    break;
                case Direction.SouthEast:
                    rowCounter++;
                    colCounter++;
                    while (rowCounter < 8 && colCounter < 8)
                    {
                        if (Bord[rowCounter, colCounter] == OppositeColor(AandeBeurt))
                        {
                            temp.Add((rowCounter, colCounter));
                        }
                        else if (Bord[rowCounter, colCounter] == AandeBeurt)
                        {
                            foundSelf = true;
                            break;
                        }
                        else
                            break;
                        rowCounter++;
                        colCounter++;
                    }
                    break;
                case Direction.South:
                    rowCounter++;
                    while (rowCounter < 8)
                    {
                        if (Bord[rowCounter, colCounter] == OppositeColor(AandeBeurt))
                        {
                            temp.Add((rowCounter, colCounter));
                        }
                        else if (Bord[rowCounter, colCounter] == AandeBeurt)
                        {
                            foundSelf = true;
                            break;
                        }
                        else
                            break;
                        rowCounter++;
                    }
                    break;
                case Direction.SouthWest:
                    rowCounter++;
                    colCounter--;
                    while (rowCounter < 8 && colCounter > 0)
                    {
                        if (Bord[rowCounter, colCounter] == OppositeColor(AandeBeurt))
                        {
                            temp.Add((rowCounter, colCounter));
                        }

ReversiApp/Controllers/SpelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReversiApp.DAL;
using ReversiApp.Models;

namespace ReversiApp.Controllers
{
    [Authorize(Roles = "Speler")]
    public class SpelController : Controller
    {
        private readonly ReversiContext _context;

        public SpelController(ReversiContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var speler = await _context.Spelers
                .Include(s => s.Spel)
                .FirstOrDefaultAsync(m => m.Id == int.Parse(User.Claims.ToArray()[0].Value));

            if (speler.Spel == null)
            {
                var games = await _context.Spellen
                    .Include(g => g.Spelers)
                    .Where(g => g.Spelers.Count < 2)
                    .Where(g => !g.Spelers.Contains(speler))
                    .ToListAsync();

                if (games == null)
                {
                    return View("List", new List<Spel>());
                }

                games = games.Where(g => !g.Afgelopen()).ToList();

                return View("List", games);
            }

            return View("Index", speler);
        }

        // GET: Spel/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Spel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Omschrijving,Token,SerializeBord,AandeBeurt")] Spel spel)
        {
            if (ModelState.IsValid)
            {
                var userId = int.Parse(User.Claims.ToArray()[0].Value);
                var user = await _context.Spelers.FindAsync(userId);

                spel.Spelers = new List<Speler>();

                spel.Spelers.Add(user);
                _context.Add(spel);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(spel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> JoinGame([Bind("ID")] Spel spel)
        {
            var foundGame = await _context.Spellen.FindAsync(spel.ID);
            var user = await _context.Spelers.FindAsync(int.Parse(User.Claims.ToArray()[0].Value));

            if (foundGame == null)
            {
                return RedirectToAction("Index");
            }

            user.Spel = foundGame;
            user.SpelId = foundGame.ID;

            _context.Update(user);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

ReversiApp/Views/Spel/Create.cshtml
@model ReversiApp.Models.Spel

@{
    Layout = "_Layout";
}

<div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">New Game</h2>
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <form asp-controller="Spel" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Omschrijving">
                <label class="mdl-textfield__label" asp-for="Omschrijving"></label>
                <span asp-validation-for="Omschrijving" class="text-danger"></span>
            </div>
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" style="width: 100%;">
                Create
            </button>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" asp-controller="Spel" asp-action="Index">
                    Back
                </a>
            </div>
        </form>
    </div>
</div>

ReversiApp/Views/Spel/Index.cshtml
@model ReversiApp.Models.Speler

@{
    Layout = "_Layout";
}

<div id="app">
    <reversi-game></reversi-game>
    <div id="snackbar" class="mdl-js-snackbar mdl-snackbar">
        <div class="mdl-snackbar__text"></div>
        <button class="mdl-snackbar__action" type="button"></button>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        window.token = "@Model.Spel.Token";
        window.playerToken = "@Model.Token";
    </script>
    <script src="~/js/bundle.min.js"></script>
}

ReversiApp/Views/Spel/List.cshtml
@model IEnumerable<ReversiApp.Models.Spel>
@{
    ViewData["Title"] = "List";
    Layout = "_Layout";
}

<div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Games</h2>
    </div>
    <div class="mdl-card__actions mdl-card--border">
        @if (Model.ToList().Count > 0)
        {
            <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="width: 100%;">
                <thead>
                    <tr>
                        <th class="mdl-data-table__cell--non-numeric">Description</th>
                        <th class="mdl-data-table__cell--non-numeric"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var game in Model)
                    {
                        <tr>
                            <td>@game.Omschrijving</td>
                            <td>
                                <form asp-controller="Spel" asp-action="JoinGame" method="post">
                                    <input type="hidden" asp-for="@game.ID" name="ID" />
                                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                                        Join
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
    <div class="mdl-card__menu">
        <a asp-controller="Spel" asp-action="Create" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect mdl-button--accent">
            <i class="material-icons">add</i>
        </a>
    </div>
</div>