ReversiApp/Models/Speler.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ReversiApp.Models
{
    public class Speler
    {
        public int Id { get; set; }
        [DisplayName("Gebruikersnaam")]
        [Required(ErrorMessage = "Er is geen gebruikersnaam ingevuld")]
        public string Naam { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Er is geen wachtwoord ingevuld!")]
        [RegularExpression(
            "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[@#$%^&+=!])([a-zA-Z0-9]).*$",
            ErrorMessage = "Minimaal 1 normale letter, 1 cijfer, 1 speciaal symbool!"
        )]
        public string Wachtwoord { get; set; }
        [Required(ErrorMessage = "Er is geen emailadres ingevuld!")]
        [EmailAddress(ErrorMessage = "Er is geen geldige emailadres ingevuld!")]
        public string Email { get; set; }
        public string Token { get; set; } = Guid.NewGuid().ToString();
        public Kleur? Kleur { get; set; }
        public Rol Rol { get; set; } = Rol.Speler;
        public bool TwoFactorAuth { get; set; } = false;

        [ForeignKey("Spel")]
        public int? SpelId { get; set; }
        public Spel Spel { get; set; }
    }
}

ReversiApp/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Web.Helpers;
using Google.Authenticator;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using ReversiApp.DAL;
using ReversiApp.Models;

namespace ReversiApp.Controllers
{
    public class AuthController : Controller
    {
        private readonly ReversiContext _context;

        public AuthController(ReversiContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Spel");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Id,Naam,Wachtwoord,Email")] Speler speler)
        {
            var httpClient = new HttpClient();
            var token = Request.Form["g-recaptcha-response"];
            var res = await httpClient.GetAsync($"https://www.google.com/recaptcha/api/siteverify?secret=6LdHwgcUAAAAAAf5E399jMeZF5yepc8l1pnYsSSF&response={token}");
            var jsonResponse = res.Content.ReadAsStringAsync().Result;
            dynamic jsonData = JObject.Parse(jsonResponse);

            if (jsonData.success != "true")
            {
                ViewData["Error"] = "Captcha empty!";
                return View("Login", speler);
            }

            var user = _context.Spelers.FirstOrDefault(i => i.Email == speler.Email);

            if (user == null)
            {
                ViewData["Error"] = "User not found!";
                return View("Login", speler);
            }

            if (!Crypto.VerifyHashedPassword(user.Wachtwoord, speler.Wachtwoord))
            {
                ViewData["Error"] = "The credentials does not match!";
                return View("Login", speler);
            }

            if (user.TwoFactorAuth)
            {
                TwoFactorAuthenticator twoFactorAuthenticator = new TwoFactorAuthenticator();
                string userUniqueKey = user.Email + user.Token;
                var setupInfo = twoFactorAuthenticator.GenerateSetupCode("Reversi - wilkodekers.hbo-ict.org", speler.Email, Encoding.ASCII.GetBytes(userUniqueKey), 10);

                HttpContext.Session.SetString("UserEmail", speler.Email);
                HttpContext.Session.SetString("UserUniqueKey", userUniqueKey);

                ViewBag.BarcodeImageUrl = setupInfo.QrCodeSetupImageUrl;
                ViewBag.SetupCode = setupInfo.ManualEntryKey;

                return View("Verify");
            }

            ClaimsIdentity identity = new ClaimsIdentity(GetUserRoleClaims(user), CookieAuthenticationDefaults.AuthenticationScheme);
            ClaimsPrincipal principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

            return RedirectToAction("Index", "Spel");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TwoFactorAuthenticate(string codeDigit)
        {
            TwoFactorAuthenticator TwoFacAuth = new TwoFactorAuthenticator();
            string UserUniqueKey = HttpContext.Session.GetString("UserUniqueKey");

            if (TwoFacAuth.ValidateTwoFactorPIN(UserUniqueKey, codeDigit))
            {
                var user = _context.Spelers.FirstOrDefault(i => i.Email == HttpContext.Session.GetString("UserEmail"));

                if (user == null)
                {
                    return RedirectToAction("Login");
                }

                ClaimsIdentity identity = new ClaimsIdentity(GetUserRoleClaims(user), CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                return RedirectToAction("Index", "Spel");
            }

            return RedirectToAction("Login");
        }

        public IActionResult Register()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Spel");
            }

            return Redirect("/Speler/Create");
        }

        private IEnumerable<Claim> GetUserRoleClaims(Speler speler)
        {
            return new List<Claim>()
            {
                new Claim(ClaimTypes.NameIdentifier, speler.Id.ToString()),
                new Claim(ClaimTypes.Name, speler.Naam),
                new Claim(ClaimTypes.Email, speler.Email),
                new Claim(ClaimTypes.Role, speler.Rol.ToString()),
                new Claim(ClaimTypes.Authentication, speler.Token),
            };
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }
    }
}

ReversiApp/Controllers/SpelerController.cs
using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Helpers;
using Google.Authenticator;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReversiApp.DAL;
using ReversiApp.Models;

namespace ReversiApp.Controllers
{
    public class SpelerController : Controller
    {
        private readonly ReversiContext _context;

        public SpelerController(ReversiContext context)
        {
            _context = context;
        }

        // GET: Speler/Details
        [Authorize(Roles = "Speler")]
        public async Task<IActionResult> Details()
        {
            var speler = await _context.Spelers
                .Include(s => s.Spel)
                .FirstOrDefaultAsync(m => m.Id == int.Parse(User.Claims.ToArray()[0].Value));
            if (speler == null)
            {
                return NotFound();
            }

            if (speler.TwoFactorAuth)
            {
                TwoFactorAuthenticator twoFactorAuthenticator = new TwoFactorAuthenticator();
                string userUniqueKey = speler.Email + speler.Token;
                var setupInfo = twoFactorAuthenticator.GenerateSetupCode("Reversi - wilkodekkers.hbo-ict.org", speler.Email, Encoding.ASCII.GetBytes(userUniqueKey), 10);

                HttpContext.Session.SetString("UserEmail", speler.Email);
                HttpContext.Session.SetString("UserUniqueKey", userUniqueKey);

                ViewBag.BarcodeImageUrl = setupInfo.QrCodeSetupImageUrl;
                ViewBag.SetupCode = setupInfo.ManualEntryKey;
            }

            ViewBag.TotalGames = _context.Spellen.Where(s => s.ID == speler.Id).Count();

            return View(speler);
        }

        // GET: Speler/Create
        public IActionResult Create()
        {
            ViewData["SpelId"] = new SelectList(_context.Spellen, "ID", "SerializeBord");
            return View();
        }

        // POST: Speler/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naam,Wachtwoord,Email")] Speler speler)
        {
            if (ModelState.IsValid)
            {
                speler.Wachtwoord = Crypto.HashPassword(speler.Wachtwoord);
                _context.Add(speler);
                await _context.SaveChangesAsync();
                return Redirect("/Auth/Login");
            }
            else
            {
                return Redirect("/Speler/Create");
            }
        }

        // GET: Speler/Edit/5
        [Authorize(Roles = "Speler")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speler = await _context.Spelers.FindAsync(id);
            if (speler == null)
            {
                return NotFound();
            }
            ViewData["SpelId"] = new SelectList(_context.Spellen, "ID", "SerializeBord", speler.SpelId);
            return View(speler);
        }

        // POST: Speler/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Speler")]
        public async Task<IActionResult> Edit([Bind("Id,Naam,Email,TwoFactorAuth,Wachtwoord")] Speler speler)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(speler);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpelerExists(speler.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("/Speler/Details");
            }
            ViewData["SpelId"] = new SelectList(_context.Spellen, "ID", "SerializeBord", speler.SpelId);
            return Redirect("/Speler/Details");
        }

        private bool SpelerExists(int id)
        {
            return _context.Spelers.Any(e => e.Id == id);
        }

        public IActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ForgotPassword([Bind("Id,Naam,Email,TwoFactorAuth,Wachtwoord")] Speler speler, string codeDigit)
        {
            TwoFactorAuthenticator TwoFacAuth = new TwoFactorAuthenticator();
            Speler user = _context.Spelers.FirstOrDefault(i => i.Email == speler.Email);

            if (user == null)
            {
                ViewBag.Error = "Invalid email";
                return View(speler);
            }

            string secret = user.Email + user.Token;

            if (!TwoFacAuth.ValidateTwoFactorPIN(secret, codeDigit))
            {
                ViewBag.Error = "Invalid code";
                return View(user);
            }

            user.Wachtwoord = Crypto.HashPassword(speler.Wachtwoord);
            _context.Spelers.Update(user);
            await _context.SaveChangesAsync();

            return Redirect("/Auth/Login");
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(string password1, string password2)
        {
            if (password1.Equals(password2))
            {
                int playerId = int.Parse(User.Claims.ToArray()[0].Value);

                var player = _context.Spelers.Find(playerId);
                player.Wachtwoord = Crypto.HashPassword(password1);
                _context.Update(player);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Spel");
            }

            return View();
        }
    }
}

ReversiApp/Views/Speler/ChangePassword.cshtml
@model ReversiApp.Models.Speler

@{
    ViewData["Title"] = "ChangePassword";
    Layout = "_Layout";
}

<div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Change Password</h2>
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <form asp-controller="Speler" asp-action="ChangePassword" method="post">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="password" name="password1">
                <label class="mdl-textfield__label" for="password1">Password</label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="password" name="password2">
                <label class="mdl-textfield__label" for="password2">Repeat password</label>
            </div>
            <div id="html_element"></div>
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" style="width: 100%;">
                Save
            </button>
        </form>
    </div>
</div>

ReversiApp/Views/Speler/Create.cshtml
@model ReversiApp.Models.Speler

@{
    ViewData["Title"] = "Register";
    Layout = "_Layout";
}

<div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Register</h2>
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <form asp-controller="Speler" asp-action="Create">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Naam">
                <label class="mdl-textfield__label" asp-for="Naam"></label>
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Email">
                <label class="mdl-textfield__label" asp-for="Email"></label>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Wachtwoord">
                <label class="mdl-textfield__label" asp-for="Wachtwoord"></label>
                <span asp-validation-for="Wachtwoord" class="text-danger"></span>
            </div>
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" style="width: 100%;">
                Register
            </button>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" asp-controller="Auth" asp-action="Login">
                    Login
                </a>
            </div>
        </form>
    </div>
</div>

ReversiApp/Views/Speler/Details.cshtml
@model ReversiApp.Models.Speler

@{
    Layout = "_Layout";
}

<div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Account</h2>
    </div>
    <div class="mdl-card__actions mdl-card--border">
        @if (Model.TwoFactorAuth)
        {
            <img src="@ViewBag.BarcodeImageUrl" style="max-width: 50%;" class="float-right" alt="BarcodeImageUrl" />
        }
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Wachtwoord" />
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Naam">
                <label class="mdl-textfield__label" asp-for="Naam"></label>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Email">
                <label class="mdl-textfield__label" asp-for="Email"></label>
            </div>
            <label class="mdl-switch mdl-js-switch mdl-js-ripple-effect" for="switch-1">
                <input type="checkbox" id="switch-1" class="mdl-switch__input" asp-for="TwoFactorAuth">
                <span class="mdl-switch__label">Two Factor Autentication</span>
            </label>
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" style="width: 100%;">
                Save
            </button>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


}

ReversiApp/Views/Speler/ForgotPassword.cshtml
@model ReversiApp.Models.Speler

@{
    ViewData["Title"] = "ForgotPassword";
    Layout = "_Layout";
}

<div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">Forgot Password</h2>
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <form asp-controller="Speler" asp-action="ForgotPassword" method="post">
            <p class="text-danger">@ViewBag.Error</p>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Email">
                <label class="mdl-textfield__label" asp-for="Email"></label>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" asp-for="Wachtwoord">
                <label class="mdl-textfield__label" asp-for="Wachtwoord"></label>
                <span asp-validation-for="Wachtwoord" class="text-danger"></span>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" name="codeDigit">
                <label class="mdl-textfield__label" for="codeDigit">Code Digit</label>
            </div>
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" style="width: 100%;">
                Save
            </button>
            <div class="mdl-card__actions mdl-card--border">
                <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" asp-controller="Auth" asp-action="Login">
                    Login
                </a>
            </div>
        </form>
    </div>
</div>